const githubResult = """{
  "total_count": 449,
  "incomplete_results": false,
  "items": [
    {
      "login": "Reiko",
      "id": 916936,
      "node_id": "MDQ6VXNlcjkxNjkzNg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/916936?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Reiko",
      "html_url": "https://github.com/Reiko",
      "followers_url": "https://api.github.com/users/Reiko/followers",
      "following_url": "https://api.github.com/users/Reiko/following{/other_user}",
      "gists_url": "https://api.github.com/users/Reiko/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Reiko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Reiko/subscriptions",
      "organizations_url": "https://api.github.com/users/Reiko/orgs",
      "repos_url": "https://api.github.com/users/Reiko/repos",
      "events_url": "https://api.github.com/users/Reiko/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Reiko/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "24",
      "id": 1859160,
      "node_id": "MDQ6VXNlcjE4NTkxNjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1859160?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/24",
      "html_url": "https://github.com/24",
      "followers_url": "https://api.github.com/users/24/followers",
      "following_url": "https://api.github.com/users/24/following{/other_user}",
      "gists_url": "https://api.github.com/users/24/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/24/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/24/subscriptions",
      "organizations_url": "https://api.github.com/users/24/orgs",
      "repos_url": "https://api.github.com/users/24/repos",
      "events_url": "https://api.github.com/users/24/events{/privacy}",
      "received_events_url": "https://api.github.com/users/24/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "running",
      "id": 56003670,
      "node_id": "MDQ6VXNlcjU2MDAzNjcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/56003670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/running",
      "html_url": "https://github.com/running",
      "followers_url": "https://api.github.com/users/running/followers",
      "following_url": "https://api.github.com/users/running/following{/other_user}",
      "gists_url": "https://api.github.com/users/running/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/running/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/running/subscriptions",
      "organizations_url": "https://api.github.com/users/running/orgs",
      "repos_url": "https://api.github.com/users/running/repos",
      "events_url": "https://api.github.com/users/running/events{/privacy}",
      "received_events_url": "https://api.github.com/users/running/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Reikon95",
      "id": 38852603,
      "node_id": "MDQ6VXNlcjM4ODUyNjAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/38852603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Reikon95",
      "html_url": "https://github.com/Reikon95",
      "followers_url": "https://api.github.com/users/Reikon95/followers",
      "following_url": "https://api.github.com/users/Reikon95/following{/other_user}",
      "gists_url": "https://api.github.com/users/Reikon95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Reikon95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Reikon95/subscriptions",
      "organizations_url": "https://api.github.com/users/Reikon95/orgs",
      "repos_url": "https://api.github.com/users/Reikon95/repos",
      "events_url": "https://api.github.com/users/Reikon95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Reikon95/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "TBXin",
      "id": 1242348,
      "node_id": "MDQ6VXNlcjEyNDIzNDg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1242348?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TBXin",
      "html_url": "https://github.com/TBXin",
      "followers_url": "https://api.github.com/users/TBXin/followers",
      "following_url": "https://api.github.com/users/TBXin/following{/other_user}",
      "gists_url": "https://api.github.com/users/TBXin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TBXin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TBXin/subscriptions",
      "organizations_url": "https://api.github.com/users/TBXin/orgs",
      "repos_url": "https://api.github.com/users/TBXin/repos",
      "events_url": "https://api.github.com/users/TBXin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TBXin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ReikoR",
      "id": 1595938,
      "node_id": "MDQ6VXNlcjE1OTU5Mzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1595938?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ReikoR",
      "html_url": "https://github.com/ReikoR",
      "followers_url": "https://api.github.com/users/ReikoR/followers",
      "following_url": "https://api.github.com/users/ReikoR/following{/other_user}",
      "gists_url": "https://api.github.com/users/ReikoR/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ReikoR/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ReikoR/subscriptions",
      "organizations_url": "https://api.github.com/users/ReikoR/orgs",
      "repos_url": "https://api.github.com/users/ReikoR/repos",
      "events_url": "https://api.github.com/users/ReikoR/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ReikoR/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikokoro",
      "id": 22475578,
      "node_id": "MDQ6VXNlcjIyNDc1NTc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/22475578?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikokoro",
      "html_url": "https://github.com/reikokoro",
      "followers_url": "https://api.github.com/users/reikokoro/followers",
      "following_url": "https://api.github.com/users/reikokoro/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikokoro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikokoro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikokoro/subscriptions",
      "organizations_url": "https://api.github.com/users/reikokoro/orgs",
      "repos_url": "https://api.github.com/users/reikokoro/repos",
      "events_url": "https://api.github.com/users/reikokoro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikokoro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "110",
      "id": 1701009,
      "node_id": "MDQ6VXNlcjE3MDEwMDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1701009?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/110",
      "html_url": "https://github.com/110",
      "followers_url": "https://api.github.com/users/110/followers",
      "following_url": "https://api.github.com/users/110/following{/other_user}",
      "gists_url": "https://api.github.com/users/110/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/110/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/110/subscriptions",
      "organizations_url": "https://api.github.com/users/110/orgs",
      "repos_url": "https://api.github.com/users/110/repos",
      "events_url": "https://api.github.com/users/110/events{/privacy}",
      "received_events_url": "https://api.github.com/users/110/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "burakon",
      "id": 13530022,
      "node_id": "MDQ6VXNlcjEzNTMwMDIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/13530022?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/burakon",
      "html_url": "https://github.com/burakon",
      "followers_url": "https://api.github.com/users/burakon/followers",
      "following_url": "https://api.github.com/users/burakon/following{/other_user}",
      "gists_url": "https://api.github.com/users/burakon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/burakon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/burakon/subscriptions",
      "organizations_url": "https://api.github.com/users/burakon/orgs",
      "repos_url": "https://api.github.com/users/burakon/repos",
      "events_url": "https://api.github.com/users/burakon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/burakon/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikoNeko",
      "id": 7728615,
      "node_id": "MDQ6VXNlcjc3Mjg2MTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7728615?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikoNeko",
      "html_url": "https://github.com/reikoNeko",
      "followers_url": "https://api.github.com/users/reikoNeko/followers",
      "following_url": "https://api.github.com/users/reikoNeko/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikoNeko/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikoNeko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikoNeko/subscriptions",
      "organizations_url": "https://api.github.com/users/reikoNeko/orgs",
      "repos_url": "https://api.github.com/users/reikoNeko/repos",
      "events_url": "https://api.github.com/users/reikoNeko/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikoNeko/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "nadoyama-reiko",
      "id": 2723924,
      "node_id": "MDQ6VXNlcjI3MjM5MjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2723924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nadoyama-reiko",
      "html_url": "https://github.com/nadoyama-reiko",
      "followers_url": "https://api.github.com/users/nadoyama-reiko/followers",
      "following_url": "https://api.github.com/users/nadoyama-reiko/following{/other_user}",
      "gists_url": "https://api.github.com/users/nadoyama-reiko/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nadoyama-reiko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nadoyama-reiko/subscriptions",
      "organizations_url": "https://api.github.com/users/nadoyama-reiko/orgs",
      "repos_url": "https://api.github.com/users/nadoyama-reiko/repos",
      "events_url": "https://api.github.com/users/nadoyama-reiko/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nadoyama-reiko/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikor0x",
      "id": 17055610,
      "node_id": "MDQ6VXNlcjE3MDU1NjEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/17055610?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikor0x",
      "html_url": "https://github.com/reikor0x",
      "followers_url": "https://api.github.com/users/reikor0x/followers",
      "following_url": "https://api.github.com/users/reikor0x/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikor0x/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikor0x/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikor0x/subscriptions",
      "organizations_url": "https://api.github.com/users/reikor0x/orgs",
      "repos_url": "https://api.github.com/users/reikor0x/repos",
      "events_url": "https://api.github.com/users/reikor0x/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikor0x/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikkaps",
      "id": 22895810,
      "node_id": "MDQ6VXNlcjIyODk1ODEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/22895810?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikkaps",
      "html_url": "https://github.com/reikkaps",
      "followers_url": "https://api.github.com/users/reikkaps/followers",
      "following_url": "https://api.github.com/users/reikkaps/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikkaps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikkaps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikkaps/subscriptions",
      "organizations_url": "https://api.github.com/users/reikkaps/orgs",
      "repos_url": "https://api.github.com/users/reikkaps/repos",
      "events_url": "https://api.github.com/users/reikkaps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikkaps/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reiko516",
      "id": 2886479,
      "node_id": "MDQ6VXNlcjI4ODY0Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2886479?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reiko516",
      "html_url": "https://github.com/reiko516",
      "followers_url": "https://api.github.com/users/reiko516/followers",
      "following_url": "https://api.github.com/users/reiko516/following{/other_user}",
      "gists_url": "https://api.github.com/users/reiko516/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reiko516/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reiko516/subscriptions",
      "organizations_url": "https://api.github.com/users/reiko516/orgs",
      "repos_url": "https://api.github.com/users/reiko516/repos",
      "events_url": "https://api.github.com/users/reiko516/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reiko516/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikomagi",
      "id": 43540277,
      "node_id": "MDQ6VXNlcjQzNTQwMjc3",
      "avatar_url": "https://avatars.githubusercontent.com/u/43540277?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikomagi",
      "html_url": "https://github.com/reikomagi",
      "followers_url": "https://api.github.com/users/reikomagi/followers",
      "following_url": "https://api.github.com/users/reikomagi/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikomagi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikomagi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikomagi/subscriptions",
      "organizations_url": "https://api.github.com/users/reikomagi/orgs",
      "repos_url": "https://api.github.com/users/reikomagi/repos",
      "events_url": "https://api.github.com/users/reikomagi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikomagi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ReiKohaku",
      "id": 51786921,
      "node_id": "MDQ6VXNlcjUxNzg2OTIx",
      "avatar_url": "https://avatars.githubusercontent.com/u/51786921?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ReiKohaku",
      "html_url": "https://github.com/ReiKohaku",
      "followers_url": "https://api.github.com/users/ReiKohaku/followers",
      "following_url": "https://api.github.com/users/ReiKohaku/following{/other_user}",
      "gists_url": "https://api.github.com/users/ReiKohaku/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ReiKohaku/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ReiKohaku/subscriptions",
      "organizations_url": "https://api.github.com/users/ReiKohaku/orgs",
      "repos_url": "https://api.github.com/users/ReiKohaku/repos",
      "events_url": "https://api.github.com/users/ReiKohaku/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ReiKohaku/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikonakajima",
      "id": 1471646,
      "node_id": "MDQ6VXNlcjE0NzE2NDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1471646?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikonakajima",
      "html_url": "https://github.com/reikonakajima",
      "followers_url": "https://api.github.com/users/reikonakajima/followers",
      "following_url": "https://api.github.com/users/reikonakajima/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikonakajima/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikonakajima/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikonakajima/subscriptions",
      "organizations_url": "https://api.github.com/users/reikonakajima/orgs",
      "repos_url": "https://api.github.com/users/reikonakajima/repos",
      "events_url": "https://api.github.com/users/reikonakajima/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikonakajima/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikoch",
      "id": 8436725,
      "node_id": "MDQ6VXNlcjg0MzY3MjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8436725?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikoch",
      "html_url": "https://github.com/reikoch",
      "followers_url": "https://api.github.com/users/reikoch/followers",
      "following_url": "https://api.github.com/users/reikoch/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikoch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikoch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikoch/subscriptions",
      "organizations_url": "https://api.github.com/users/reikoch/orgs",
      "repos_url": "https://api.github.com/users/reikoch/repos",
      "events_url": "https://api.github.com/users/reikoch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikoch/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reiko-ushigome",
      "id": 14106870,
      "node_id": "MDQ6VXNlcjE0MTA2ODcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/14106870?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reiko-ushigome",
      "html_url": "https://github.com/reiko-ushigome",
      "followers_url": "https://api.github.com/users/reiko-ushigome/followers",
      "following_url": "https://api.github.com/users/reiko-ushigome/following{/other_user}",
      "gists_url": "https://api.github.com/users/reiko-ushigome/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reiko-ushigome/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reiko-ushigome/subscriptions",
      "organizations_url": "https://api.github.com/users/reiko-ushigome/orgs",
      "repos_url": "https://api.github.com/users/reiko-ushigome/repos",
      "events_url": "https://api.github.com/users/reiko-ushigome/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reiko-ushigome/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikoppu",
      "id": 73151673,
      "node_id": "MDQ6VXNlcjczMTUxNjcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/73151673?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikoppu",
      "html_url": "https://github.com/reikoppu",
      "followers_url": "https://api.github.com/users/reikoppu/followers",
      "following_url": "https://api.github.com/users/reikoppu/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikoppu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikoppu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikoppu/subscriptions",
      "organizations_url": "https://api.github.com/users/reikoppu/orgs",
      "repos_url": "https://api.github.com/users/reikoppu/repos",
      "events_url": "https://api.github.com/users/reikoppu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikoppu/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reiko321",
      "id": 46850532,
      "node_id": "MDQ6VXNlcjQ2ODUwNTMy",
      "avatar_url": "https://avatars.githubusercontent.com/u/46850532?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reiko321",
      "html_url": "https://github.com/reiko321",
      "followers_url": "https://api.github.com/users/reiko321/followers",
      "following_url": "https://api.github.com/users/reiko321/following{/other_user}",
      "gists_url": "https://api.github.com/users/reiko321/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reiko321/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reiko321/subscriptions",
      "organizations_url": "https://api.github.com/users/reiko321/orgs",
      "repos_url": "https://api.github.com/users/reiko321/repos",
      "events_url": "https://api.github.com/users/reiko321/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reiko321/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "RickorDD",
      "id": 6922544,
      "node_id": "MDQ6VXNlcjY5MjI1NDQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6922544?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RickorDD",
      "html_url": "https://github.com/RickorDD",
      "followers_url": "https://api.github.com/users/RickorDD/followers",
      "following_url": "https://api.github.com/users/RickorDD/following{/other_user}",
      "gists_url": "https://api.github.com/users/RickorDD/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RickorDD/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RickorDD/subscriptions",
      "organizations_url": "https://api.github.com/users/RickorDD/orgs",
      "repos_url": "https://api.github.com/users/RickorDD/repos",
      "events_url": "https://api.github.com/users/RickorDD/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RickorDD/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Reikomiao",
      "id": 15166583,
      "node_id": "MDQ6VXNlcjE1MTY2NTgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/15166583?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Reikomiao",
      "html_url": "https://github.com/Reikomiao",
      "followers_url": "https://api.github.com/users/Reikomiao/followers",
      "following_url": "https://api.github.com/users/Reikomiao/following{/other_user}",
      "gists_url": "https://api.github.com/users/Reikomiao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Reikomiao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Reikomiao/subscriptions",
      "organizations_url": "https://api.github.com/users/Reikomiao/orgs",
      "repos_url": "https://api.github.com/users/Reikomiao/repos",
      "events_url": "https://api.github.com/users/Reikomiao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Reikomiao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reiko-f",
      "id": 28795335,
      "node_id": "MDQ6VXNlcjI4Nzk1MzM1",
      "avatar_url": "https://avatars.githubusercontent.com/u/28795335?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reiko-f",
      "html_url": "https://github.com/reiko-f",
      "followers_url": "https://api.github.com/users/reiko-f/followers",
      "following_url": "https://api.github.com/users/reiko-f/following{/other_user}",
      "gists_url": "https://api.github.com/users/reiko-f/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reiko-f/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reiko-f/subscriptions",
      "organizations_url": "https://api.github.com/users/reiko-f/orgs",
      "repos_url": "https://api.github.com/users/reiko-f/repos",
      "events_url": "https://api.github.com/users/reiko-f/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reiko-f/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikop",
      "id": 1168696,
      "node_id": "MDQ6VXNlcjExNjg2OTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1168696?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikop",
      "html_url": "https://github.com/reikop",
      "followers_url": "https://api.github.com/users/reikop/followers",
      "following_url": "https://api.github.com/users/reikop/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikop/subscriptions",
      "organizations_url": "https://api.github.com/users/reikop/orgs",
      "repos_url": "https://api.github.com/users/reikop/repos",
      "events_url": "https://api.github.com/users/reikop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikop/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "reikolo",
      "id": 67831538,
      "node_id": "MDQ6VXNlcjY3ODMxNTM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/67831538?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/reikolo",
      "html_url": "https://github.com/reikolo",
      "followers_url": "https://api.github.com/users/reikolo/followers",
      "following_url": "https://api.github.com/users/reikolo/following{/other_user}",
      "gists_url": "https://api.github.com/users/reikolo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/reikolo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/reikolo/subscriptions",
      "organizations_url": "https://api.github.com/users/reikolo/orgs",
      "repos_url": "https://api.github.com/users/reikolo/repos",
      "events_url": "https://api.github.com/users/reikolo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/reikolo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ReikoLJ",
      "id": 17126971,
      "node_id": "MDQ6VXNlcjE3MTI2OTcx",
      "avatar_url": "https://avatars.githubusercontent.com/u/17126971?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ReikoLJ",
      "html_url": "https://github.com/ReikoLJ",
      "followers_url": "https://api.github.com/users/ReikoLJ/followers",
      "following_url": "https://api.github.com/users/ReikoLJ/following{/other_user}",
      "gists_url": "https://api.github.com/users/ReikoLJ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ReikoLJ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ReikoLJ/subscriptions",
      "organizations_url": "https://api.github.com/users/ReikoLJ/orgs",
      "repos_url": "https://api.github.com/users/ReikoLJ/repos",
      "events_url": "https://api.github.com/users/ReikoLJ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ReikoLJ/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Reiko-Developer",
      "id": 9553743,
      "node_id": "MDQ6VXNlcjk1NTM3NDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9553743?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Reiko-Developer",
      "html_url": "https://github.com/Reiko-Developer",
      "followers_url": "https://api.github.com/users/Reiko-Developer/followers",
      "following_url": "https://api.github.com/users/Reiko-Developer/following{/other_user}",
      "gists_url": "https://api.github.com/users/Reiko-Developer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Reiko-Developer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Reiko-Developer/subscriptions",
      "organizations_url": "https://api.github.com/users/Reiko-Developer/orgs",
      "repos_url": "https://api.github.com/users/Reiko-Developer/repos",
      "events_url": "https://api.github.com/users/Reiko-Developer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Reiko-Developer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ReikoMori",
      "id": 9301976,
      "node_id": "MDQ6VXNlcjkzMDE5NzY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9301976?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ReikoMori",
      "html_url": "https://github.com/ReikoMori",
      "followers_url": "https://api.github.com/users/ReikoMori/followers",
      "following_url": "https://api.github.com/users/ReikoMori/following{/other_user}",
      "gists_url": "https://api.github.com/users/ReikoMori/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ReikoMori/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ReikoMori/subscriptions",
      "organizations_url": "https://api.github.com/users/ReikoMori/orgs",
      "repos_url": "https://api.github.com/users/ReikoMori/repos",
      "events_url": "https://api.github.com/users/ReikoMori/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ReikoMori/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cyberhedz",
      "id": 3128895,
      "node_id": "MDQ6VXNlcjMxMjg4OTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3128895?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cyberhedz",
      "html_url": "https://github.com/cyberhedz",
      "followers_url": "https://api.github.com/users/cyberhedz/followers",
      "following_url": "https://api.github.com/users/cyberhedz/following{/other_user}",
      "gists_url": "https://api.github.com/users/cyberhedz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cyberhedz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cyberhedz/subscriptions",
      "organizations_url": "https://api.github.com/users/cyberhedz/orgs",
      "repos_url": "https://api.github.com/users/cyberhedz/repos",
      "events_url": "https://api.github.com/users/cyberhedz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cyberhedz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}""";
